### ISSUE TITLE
在树洞早期注销后无法登录

### ISSUE THREAD

**Issue by Acornagain** [treehollow/treehollow-backend#89]
各位开发者好！我是树洞早期用户，当时（为戒除网瘾）而注销了树洞账户，如今想再次登录。在登录界面输入任何密码都会显示密码错误（考虑到也在当时还没有密码登录的选择）。而在注销账号和找回密码界面，则因为需要Nonce口令而无法成功注销（早期邮件里只有验证码）。本人不知道这是否是合适的渠道反映问题，若是则麻烦各位开发者能否看看，若否则麻烦告知，我可以立即删除此issue。十分感谢！

**Comment by thuhole** [comment]
您好，请您使用您注册树洞时的邮箱向树洞网页版中留下的联系邮箱发邮件。
