### ISSUE TITLE
"treehollow-v3-backend/pkg/bot" Seems To Be Missing

### ISSUE THREAD

**Issue by yongzhengqi** [treehollow/treehollow-backend#91]
In `pkg/route/contents/route.go` and `pkg/route/contents/routeApiPOST.go`, `"treehollow-v3-backend/pkg/bot"` is imported. However, this `bot` file seems to be missing from this repo.

When runnning `go install ./...`, the above absence will cause this error: `pkg/route/contents/route.go:14:2: package treehollow-v3-backend/pkg/bot is not in GOROOT`.

Looking forward to your reply.

**Comment by yongzhengqi** [comment]
It seems to be a modified version of [https://pkg.go.dev/github.com/liquiddeath13/reactivetgbot](https://pkg.go.dev/github.com/liquiddeath13/reactivetgbot).

**Comment by thuhole** [comment]
Thanks for your bug report, sorry this was because there was a file that was forgotten to be git-added. You can git pull and try again now.

**Comment by yongzhengqi** [comment]
It works. Thank you for your help.
